from django.urls import path

from . import views

urlpatterns = [
    path('', views.legacy_page, {'page_name': 'home'}, name='home'),
    path('about/', views.legacy_page, {'page_name': 'about'}, name='about'),
    path('rights/', views.legacy_page, {'page_name': 'rights'}, name='rights'),
    path('articles/', views.legacy_page, {'page_name': 'articles'}, name='articles'),
    path('cases/', views.legacy_page, {'page_name': 'cases'}, name='cases'),
    path('crimes/', views.legacy_page, {'page_name': 'crimes'}, name='crimes'),
    path('freedom/', views.legacy_page, {'page_name': 'freedom'}, name='freedom'),
    path('helpline/', views.legacy_page, {'page_name': 'helpline'}, name='helpline'),
    path('quiz/', views.quiz, name='quiz'),
    path('quiz/api/generate/', views.generate_quiz, name='quiz_generate'),
    path('quiz/api/score/', views.score_quiz, name='quiz_score'),
    path('survey/', views.survey, name='survey'),
    path('accounts/register/', views.register, name='register'),
    path('accounts/login/', views.user_login, name='login'),
    path('accounts/logout/', views.user_logout, name='logout'),
    path('accounts/google/login/', views.google_login, name='google_login'),
    path('accounts/google/callback/', views.google_callback, name='google_callback'),
    path('survey/thank-you/', views.survey_thank_you, name='survey_thank_you'),
    path('results/', views.results, name='results'),
    path('results/audio/<int:response_id>/', views.response_audio, name='response_audio'),
    path('values/sovereignty/', views.legacy_page, {'page_name': 'sovereignty'}, name='sovereignty'),
    path('values/secularism/', views.legacy_page, {'page_name': 'secularism'}, name='secularism'),
    path('values/socialism/', views.legacy_page, {'page_name': 'socialism'}, name='socialism'),
    path('values/democracy/', views.legacy_page, {'page_name': 'democracy'}, name='democracy'),
    path('values/republic/', views.legacy_page, {'page_name': 'republic'}, name='republic'),
    path('values/justice/', views.legacy_page, {'page_name': 'justice'}, name='justice'),
    path('values/liberty/', views.legacy_page, {'page_name': 'liberty'}, name='liberty'),
    path('values/equality/', views.legacy_page, {'page_name': 'equality'}, name='equality'),
    path('values/fraternity/', views.legacy_page, {'page_name': 'fraternity'}, name='fraternity'),
    path('values/dignity/', views.legacy_page, {'page_name': 'dignity'}, name='dignity'),
    path('values/unity/', views.legacy_page, {'page_name': 'unity'}, name='unity'),
    path('index.html', views.legacy_file, {'page_name': 'home'}),
    path('about.html', views.legacy_file, {'page_name': 'about'}),
    path('rights.html', views.legacy_file, {'page_name': 'rights'}),
    path('articles.html', views.legacy_file, {'page_name': 'articles'}),
    path('cases.html', views.legacy_file, {'page_name': 'cases'}),
    path('crimes.html', views.legacy_file, {'page_name': 'crimes'}),
    path('freedom.html', views.legacy_file, {'page_name': 'freedom'}),
    path('helpline.html', views.legacy_file, {'page_name': 'helpline'}),
    path('quiz.html', views.quiz),
    path('survey.html', views.survey),
    path('results.html', views.results),
    path('sovereignty.html', views.legacy_file, {'page_name': 'sovereignty'}),
    path('secularism.html', views.legacy_file, {'page_name': 'secularism'}),
    path('socialism.html', views.legacy_file, {'page_name': 'socialism'}),
    path('democracy.html', views.legacy_file, {'page_name': 'democracy'}),
    path('republic.html', views.legacy_file, {'page_name': 'republic'}),
    path('justice.html', views.legacy_file, {'page_name': 'justice'}),
    path('liberty.html', views.legacy_file, {'page_name': 'liberty'}),
    path('equality.html', views.legacy_file, {'page_name': 'equality'}),
    path('fraternity.html', views.legacy_file, {'page_name': 'fraternity'}),
    path('dignity.html', views.legacy_file, {'page_name': 'dignity'}),
    path('unity.html', views.legacy_file, {'page_name': 'unity'}),
]
