# Generated by Django 6.1.1 on 2026-09-27 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(99)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(choices=[('Commerce', 'Commerce'), ('Engineering / Tech', 'Engineering / Tech'), ('Science', 'Science'), ('Other', 'Other')], max_length=40)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year'), ('PG / Masters', 'PG / Masters'), ('PhD', 'PhD'), ('Pass out / Working', 'Pass out / Working')], max_length=30)),
                ('q8', models.CharField(blank=True, max_length=120)),
                ('q9', models.CharField(blank=True, max_length=120)),
                ('q10', models.TextField(blank=True)),
                ('q11', models.CharField(blank=True, max_length=180)),
                ('q12', models.CharField(blank=True, max_length=180)),
                ('q13', models.CharField(blank=True, max_length=180)),
                ('q14', models.TextField(blank=True)),
                ('q21', models.CharField(blank=True, max_length=120)),
                ('q22', models.CharField(blank=True, max_length=120)),
                ('q23', models.CharField(blank=True, max_length=180)),
                ('q24', models.CharField(blank=True, max_length=180)),
                ('q25', models.CharField(blank=True, max_length=120)),
                ('q26', models.TextField(blank=True)),
                ('q27', models.CharField(blank=True, max_length=120)),
                ('q28', models.CharField(blank=True, max_length=180)),
                ('q29', models.CharField(blank=True, max_length=120)),
                ('q30', models.CharField(blank=True, max_length=180)),
                ('q31', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q37', models.CharField(blank=True, max_length=150)),
                ('q38', models.CharField(blank=True, max_length=150)),
                ('q39', models.CharField(blank=True, max_length=180)),
                ('q40', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q41', models.CharField(blank=True, max_length=180)),
                ('q42', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q43', models.TextField(blank=True)),
                ('q44', models.TextField(blank=True)),
                ('q45', models.TextField(blank=True)),
                ('survey_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('audio_url', models.URLField(blank=True)),
                ('audio_status', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
